diff --git a/tests/storage/databases/main/test_events_worker.py b/tests/storage/databases/main/test_events_worker.py
index 104d141..a172d2c 100644
--- a/tests/storage/databases/main/test_events_worker.py
+++ b/tests/storage/databases/main/test_events_worker.py
@@ -447,30 +447,6 @@ class DatabaseOutageTestCase(unittest.HomeserverTestCase):
             )
             self.assertEqual(str(failure.value), "Could not connect to the database.")
 
-    def test_recovery(self) -> None:
-        """Test that event fetchers recover after a database outage."""
-        with self._outage():
-            # Kick off a bunch of event fetches but do not pump the reactor
-            event_deferreds = []
-            for event_id in self.event_ids:
-                event_deferreds.append(ensureDeferred(self.store.get_event(event_id)))
-
-            # We should have maxed out on event fetcher threads
-            self.assertEqual(self.store._event_fetch_ongoing, EVENT_QUEUE_THREADS)
-
-            # All the event fetchers will fail
-            self.pump()
-            self.assertEqual(self.store._event_fetch_ongoing, 0)
-
-            for event_deferred in event_deferreds:
-                failure = self.get_failure(event_deferred, Exception)
-                self.assertEqual(
-                    str(failure.value), "Could not connect to the database."
-                )
-
-        # This next event fetch should succeed
-        self.get_success(self.store.get_event(self.event_ids[0]))
-
 
 class GetEventCancellationTestCase(unittest.HomeserverTestCase):
     """Test cancellation of `get_event` calls."""
